### ISSUE TITLE
requirement

### ISSUE THREAD

**Issue by SoluMilken** [Yoctol/seq2vec#13]
不知道要不要多加 
tensorflow-gpu ??  
(如果同時pip install tensorflow 和 tensorflow-gpu 不知道會發生什麼事情？？）

**Comment by SoluMilken** [comment]
setup.py 還是需要tensorflow QQ  
setup(
    name='seq2vec',
    version='0.2.0',
    description='A pip package',
    license='GNU 3.0',
    author='cph',
    packages=find_packages(),
    install_requires=[
        'numpy',
        'keras',
        'yoctol_utils',
    ],
    long_description=long_description,
    classifiers=[
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.5',
]

**Comment by plliao** [comment]
#22
